language: java
 
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "uKhxIHY/mz7WONEeJHM8rOL/ZX1IC+Yggg+1xqZSGYlYrXW3gkyAHWv9uN1T\nz2bQi0GpLr38Q7GJOs2nYdNYtmboICEph1eo0mhCMnsWfxATmEu8rxGCZ8l9\no0uZk7GcVimu7MzYuR1dPlA8bC+P5LeX+SeaZDgWa2d1hlCWCo8="

after_success:
  - python .travis.addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml

notifications:
  email:
    - connid-dev@googlegroups.com
